### ISSUE TITLE
warn when a merge source refers to itself

### ISSUE THREAD

**Issue by kylrth** [slurdge/goeland#100]
I kept getting massive amounts of logs (gigabytes every few days), finally narrowed it down to goeland, and turned off debug logging, thinking the problem was solved. But I wasn't getting any emails from a particular pipe and I was confused by that. Turns out I had accidentally included the merge source in its own set of sources, causing an infinite loop. All the other pipes ran as expected, which was why I wasn't tipped off sooner.

It could be good to include a check for self-reference like that. Obviously you could still come up with contrived examples to produce infinite looping, like by having two merge sources reference each other, but this would warn users quickly if they've made a simple mistake. Thoughts?

**Comment by kylrth** [comment]
I'd be willing to write a PR for this

**Comment by slurdge** [comment]
Great catch ! I agree we should check this case.
I see two options:

1. Just check is a source is included in subsources. This will catch most (if not all) cases.
2. Add an additional parameter which is "parents" inside `FecthSource` of type slice of string and add yourself in case of merge. This would catch all cycles even those build "on purpose".

I would prefer 2. I can work on this at the end of the week, but if you want to do a PR, no problem 😄

**Comment by slurdge** [comment]
@kylrth This will be fixed on next release
