### ISSUE TITLE
Windows Defender detecting the .exe as trojan

### ISSUE THREAD

**Issue by departet** [slurdge/goeland#106]
Just wanted to let you know windows defender detects the exe as a trojan:win32/Watac.B!ml

![grafik](https://user-images.githubusercontent.com/68166825/215293036-c64074c7-66a1-43fc-9446-1188f4e56c85.png)

**Comment by slurdge** [comment]
Thanks for the heads up. I don't know why it would be flagged but I will investigate.

**Comment by slurdge** [comment]
It seems it has to do with the fact that I pack the exe with upx. I do this to conserve bandwidth as golang programs can be quite large... If you uncompress it with `upx -d <goeland.exe>` I do not have the warning anymore

**Comment by departet** [comment]
I guessed it was a false positive already. Searching the web for the definition gives a lot of results where people experienced this with selfwritten software.

**Comment by slurdge** [comment]
I've removed UPX for now.
