### ISSUE TITLE
Plain text email

### ISSUE THREAD

**Issue by valodiadeseynes** [slurdge/goeland#123]
Hi,

Could you add a plain text option? I'd rather not use HTML in emails if given the choice.

**Comment by slurdge** [comment]
Hey @valodiadeseynes ,

There is already a plain text version along the HTML version. But by judging from the other bug report, it seems you don't have it. This may be related, as is there is a bug a plain text may not be available.

Or do you mean a _only plain text_ option, where the HTML wouldn't be included ? goeland does HTML -> TXT conversion as most (if not all) the content of RSS feed is HTML formatted.

**Comment by valodiadeseynes** [comment]
If goeland includes both plain text and HTML then it's fine for me.

I'll close this issue, thanks!
