### ISSUE TITLE
Release 0.13.0 reports it's v. 0.11.0

### ISSUE THREAD

**Issue by panigrc** [slurdge/goeland#126]
**Describe the bug**
I've downloaded the release 0.13.0 from here  [goeland_linux_amd64](https://github.com/slurdge/goeland/releases/download/v0.13.0/goeland_linux_amd64) but when I execute the `version` command it reports that it is 0.11.0

**Expected behavior**
I would expect to get 0.13.0

**Screenshots**
![image](https://user-images.githubusercontent.com/645895/225433106-e48081ea-882d-43c6-8523-a93bfca76e03.png)

**Server (please complete the following information):**
 - OS: Ubuntu server 22.04

**Comment by slurdge** [comment]
Good catch ! I'll check why :)

**Comment by slurdge** [comment]
The bug is due to the fact that the 'v' part of the version is not included by the github action, either I'll have to change the regexp or I find a way to have the v included.

**Comment by slurdge** [comment]
I note that the build date & git commit aren't filled too...

**Comment by slurdge** [comment]
Version should be ok. Date & Git commit are another beast...
