### ISSUE TITLE
smtp connection timed out 

### ISSUE THREAD

**Issue by buraktplgu** [slurdge/goeland#152]
level=fatal msg="cannot create email pool: Mail Error: SMTP Connection timed out"
\Downloads\goeland> smtp connection timed out

When I give the command goeland ./goeland.exe run, which I intend to use to send news from the RSS source I created via email, it gives the above error.  Can anyone with information help me? 
(I am very new and my knowledge is really limited)

**Comment by slurdge** [comment]
What did you put as your SMTP server ?
