### ISSUE TITLE
Some relative links don't get rewritten

### ISSUE THREAD

**Issue by Cyberbeni** [slurdge/goeland#169]
**Describe the bug**
Relative links in certain RSS feeds don't get rewritten

**To Reproduce**
1. Generate email from the following feeds:
 - https://developer.apple.com/news/releases/rss/releases.rss
 - https://swordscomic.com/comic/feed/
2. Click on links in emails

**Expected behavior**
Relative links in the linked rss feed get rewritten

**Comment by Cyberbeni** [comment]
I found out that you can specify the base url for relative links, which should be more robust than trying to regex all the possible ways to write relative links:

```
<base href="https://developer.apple.com" />
```

**Comment by slurdge** [comment]
I'll look into it. You suggest that goeland manually put the `base` into the email right ?

**Comment by Cyberbeni** [comment]
I currently use different templates for this. Using `base` doesn't work if multiple feeds are merged and would need different base urls, so I don't know what would be the best solution.

**Comment by slurdge** [comment]
You are right, and even Gmail&Hotmail would filter out the base. I've added an additional rule into the "links" filter, that rewrite src&href with the correct base URL. It works in your two examples, so let's cross fingers some strange feeds won't pop out.

**Comment by slurdge** [comment]
Please try 0.16.0 and tell me if the situation is better :)

**Comment by Cyberbeni** [comment]
The newest ghcr.io docker image is still 0.15.0

**Comment by slurdge** [comment]
My bad, action is still running :)

**Comment by Cyberbeni** [comment]
It seems to be working correctly
