### ISSUE TITLE
No link included despite the includelink filter

### ISSUE THREAD

**Issue by Wobak** [slurdge/goeland#214]
**Describe the bug**
No link included despite the includelink filter

**To Reproduce**
I have example emails with the config being correctly sending emails, but no link included

**Expected behavior**
THe link being included :)

**Screenshots**
N/A

**Desktop (please complete the following information):**
Any mail client

**Additional context**
Config.toml excerpt:
```
[sources.myblog]
url = "<redacted>"
type = "feed"
filters = ["all", "unseen", "includelink"]
allow-insecure = false
```

**Comment by Wobak** [comment]
And I can see in the logs that the includelink is indeed seen : 

```
goeland-2024-thibaut  | time="2024-07-03T13:00:00Z" level=debug msg="Executing includelink filter with args: []"
goeland-2024-thibaut  | time="2024-07-03T13:00:00Z" level=info msg="After includelink: 1 feeds"
goeland-2024-thibaut  | time="2024-07-03T13:00:00Z" level=debug msg="After includelink: [{UID:66853888034...
```

**Comment by slurdge** [comment]
Check if you have:
```
include-title= true
```

In you config, or else, you won't generate titles, and therefore no back link.

Alternatively, you can use a custom made template and use the `{{.EntryURL}}` variable. The template is there:
https://github.com/slurdge/goeland/blob/master/cmd/asset/email.default.html

**Comment by Wobak** [comment]
I added include-link but not include-title. Let me add that and see with the next article, thanks. Is that documented somewhere and I missed it?

**Comment by Wobak** [comment]
Works with the include title :)

Thank you for the update, might be worth updating the README to put it in the email section I guess ?
