### ISSUE TITLE
Improve templates documentation

### ISSUE THREAD

**Issue by pztrn** [slurdge/goeland#56]
Trying to create custom template and found no documentation about placeholders for templater as well as no ability to simply get a link for entry.

**Comment by slurdge** [comment]
Hi @pztrn , you are right I did not create yet the doc for templater.
You can look at two things, the first is:
https://github.com/slurdge/goeland/blob/master/cmd/asset/email.default.html

Which will give you most of the template args. Most important is `{{.EntryContent}}` which will output the entry.

Second you can look at https://github.com/slurdge/goeland/blob/master/cmd/run.go#L125 where you can see how the args are used. I'll try to fix up some doc.

**Comment by slurdge** [comment]
Related issues, #4 and #15

**Comment by slurdge** [comment]
fixed
