### ISSUE TITLE
Aggregated weekly digest with only titles

### ISSUE THREAD

**Issue by sweenu** [slurdge/goeland#79]
First, I'd like to say I really like goeland. It's simple, yet powerful and I like the fact that it's stateless and easily configurable with a config file.

Now to my problem, what I hoped I could get by using goeland is a weekly digest of all the new articles of the blogs I follow sent to me in one email. It would look something like:

```markdown
### Weekly digest
All the new posts from last week:
#### [Blog one](https://linktotheweb.site)
* [How to make a cake?](https://linktotheblog.post)
* [Are cakes still relevant in 2022?](https://linktotheblog.post)
#### [Blog three](https://linktotheweb.site)
* [Make a pie in three steps](https://linktotheblog.post)
```
There is no `Blog two` because it won't have posted anything the past week.

However, right now this is not possible for serveral reasons from what I see in the code:
* the source url is not saved (easily fixed by adding a `URL` field to the `Source` struct).
* using the `merge` source type makes you loose the information about the subsources like `source.Title` which I would need to do what I want.
* the source information (name, title and url in the future) is not accessible via the html template.

Is this a usecase you'd like to support? If yes, is there a certain way you would like it implemented? I am down to work on this.
I believe it would be cleaner to loop over all the sources and their entries in the html template than doing in go and embedding a single long string in the html.

**Comment by slurdge** [comment]
I think this is a great idea and expands on use cases for goeland. I'm a bit busy this week, so I can't contribute much time to it.
The way I see it is aligned with what you envision, namely, add a URL in the source, keeping information up (beware that if merge keeps it, probably digest would want it too).
The last thing is the html template where it becomes trickier, as in if we add to much fields we need to be sure that they are always available or have decent fallbacks. For exemple, if one day a source is twitter (as imgur is also a source) ,we would want to have proper support for these fields.

If you want to start a PR that's fine, I'll give you my feedback on it.
